<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_field_widget_form_alter().
 */
function commerce_stores_field_widget_form_alter(&$element, FormStateInterface &$form_state, $context) {

  $user_id = \Drupal::currentUser()->id();
  $user_role = \Drupal::currentUser()->getRoles();

  if ($context['items']->getName() == 'stores') {

    if (in_array("manufacturer",$user_role)) {
      $element['#options'] = NULL;
    }

    $commerce_stores = \Drupal::entityTypeManager()->
    getStorage("commerce_store")->
    loadByProperties(['uid' => $user_id]);

    if ($commerce_stores) {

      $element['#options'] = false;

      $link_login = t('add own commerce store');
      $url_stores = '/admin/commerce/config/stores';

      $element['#suffix'] = "<div class='product-manufacturer'><a href='".$url_stores."'>".$link_login."</a></div>";

    } else {

      foreach ($commerce_stores as $commerce_store) {

        $element['#options'][$commerce_store->id()]=$commerce_store->getName();
      }
    }
    return $element;
  }
}
//
///**
// * Implements  hook_form_alter().
// */
//function commerce_stores_form_alter(&$form, FormStateInterface $form_state, $form_id) {
//
//  if($form_id=="commerce_stock_transactions1") {
//
//    kint($form);
//
//    $form['name'] = array(
//      '#type' => 'textfield',
//      '#title' => t('Name'),
//      '#description' => t(''),
//      '#maxlength' => 64,
//      '#size' => 64,
//      '#weight' => '0',
//    );
//  }
//}