<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_field_widget_form_alter().
 */
function distributor_role_field_widget_form_alter(&$element, FormStateInterface &$form_state, $context) {
  $user_id = \Drupal::currentUser()->id();
  $user_role = \Drupal::currentUser()->getRoles();
  if ($context['items']->getName() == 'stores') {
    if ( in_array("administrator", $user_role)) { }
    elseif (in_array("distributor", $user_role) || in_array("producer", $user_role)) {
      $element['#options'] = NULL;
      $stores = \Drupal\commerce_store\Entity\Store::loadMultiple();
      foreach ($stores as $store_id => $store) {
        if ($user_id == $store->getOwnerId()) {
          $element['#options'][$store_id] = $store->getName();
        }
      }
    }
    return $element;
  }
}


